// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkWEYz3KFq2y-a7W_xkhK4S1ttue95P6w',
    appId: '1:852391466375:web:1d92e02247c785a2f12f22',
    messagingSenderId: '852391466375',
    projectId: 'idoc-4674f',
    authDomain: 'idoc-4674f.firebaseapp.com',
    storageBucket: 'idoc-4674f.firebasestorage.app',
    measurementId: 'G-T4X0D40QPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBmyzAg4M1lj23iHk5Ci-_00yJ7Y-tF0c',
    appId: '1:852391466375:android:1c73ef05cf0b6b52f12f22',
    messagingSenderId: '852391466375',
    projectId: 'idoc-4674f',
    storageBucket: 'idoc-4674f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkWEYz3KFq2y-a7W_xkhK4S1ttue95P6w',
    appId: '1:852391466375:web:f4c55ceb2877f91af12f22',
    messagingSenderId: '852391466375',
    projectId: 'idoc-4674f',
    authDomain: 'idoc-4674f.firebaseapp.com',
    storageBucket: 'idoc-4674f.firebasestorage.app',
    measurementId: 'G-ZEKPYSTHYJ',
  );
}
